apiVersion: apps/v1
kind: Deployment
metadata:
  name: interview-yeah
spec:
  replicas: 1
  selector:
    matchLabels:
      app: interview-yeah
  template:
    metadata:
      labels:
        app: interview-yeah
    spec:
      containers:
        - name: interview-yeah
          image: chad0/vapi-ai-inter:v3
          ports:
            - containerPort: 5173
---
apiVersion: v1
kind: Service
metadata:
  name: vapi-service
spec:
  type: LoadBalancer
  selector:
    app: interview-yeah
  ports:
    - port: 80
      targetPort: 5173


